# Site settings
title: AIT Wiki
email: mdteamait@gmail.com
description: Information about the Tardis Mod Adventures in Time
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

#baseurl: "ait-fabric-1.20.1" # the subpath of your site, e.g. /blog/
url: "https://loqor.dev/" # the base hostname & protocol for your site
twitter_username: Loqorium
github_username: Loqor
permalink: /:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/Loqor/ait/blob/main/docs/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/Loqor/ait/new/main/docs
show_excerpts: true
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
# disqus_shortname: lixizhi
# disqus_url: "http://lixizhi.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
